In [20]:

import numpy as np
from services.gameManager import GameManager
from models.game import Game



In [21]:
gamemanager = GameManager(game)

In [22]:
!pwd

/home/schmijul/source/repos/robotarm


In [23]:
import moves

In [24]:
moves.legal_moves_generator(game.board, game.turn)

{(0, 1): array([1, 1, 2, 2, 0, 2, 2, 2, 2]),
 (0, 2): array([1, 2, 1, 2, 0, 2, 2, 2, 2]),
 (1, 0): array([1, 2, 2, 1, 0, 2, 2, 2, 2]),
 (1, 2): array([1, 2, 2, 2, 0, 1, 2, 2, 2]),
 (2, 0): array([1, 2, 2, 2, 0, 2, 1, 2, 2]),
 (2, 1): array([1, 2, 2, 2, 0, 2, 2, 1, 2]),
 (2, 2): array([1, 2, 2, 2, 0, 2, 2, 2, 1])}

In [25]:
import dlmodel as dlm

In [26]:
weak_mlp = dlm.build_model(10)
strong_mlp = dlm.build_model(100)

In [27]:
import training as t

In [28]:
num_played_games = 0
while(num_played_games < 1000):
    game = Game()
    game.toss()
    weak_mlp = t.train(weak_mlp, game)[0]


    game = Game()
    game.toss()
    strong_mlp = t.train(weak_mlp, game)[1]
    
    num_played_games +=1

1/1 [==============================] - 0s 24ms/step
[[1 0 0]
 [1 1 1]
 [0 1 0]]
1/1 [==============================] - 0s 21ms/step
[[0 2 0]
 [1 0 0]
 [1 1 1]]
1/1 [==============================] - 0s 20ms/step


KeyboardInterrupt: 